### PR TITLE
fix: safe auth

### LINKED ISSUE #1649: Centrifuge Safe App - Onboarding Issue
[Bug report](https://airtable.com/appHHbzGGPukSqFcM/tblcNy7XXqQdtTh9O/viwfbnigFtnLzEuWz/recjSeOhHTpbMnX6G?blocks=hide)

**Environment:** macOS
**Steps to Reproduce:**
* Try onboarding through the [centrifuge safe app](https://app.safe.global/apps/open?safe=eth:0xfF501B324DC6d78dC9F983f140B9211c3EdB4dc7&appUrl=https%3A%2F%2Fapp.centrifuge.io) 
and try to onboard as a new user

**Expected Result:** 
* Onboarding flow starts
**Actual Result:** 
* Once the investor begins onboarding by connecting wallet, checking that they agree to the terms and signs the safe transaction to approve it says success but the page doesn't move on in the onboarding flow. 

**Additional Information:**
Has been reported from a big investor (2M)

Image
Image

### PR DESCRIPTION
**Pull request by jpangelle**
### Description

This pull request fixes an issue when authenticating on the `/onboarding` page with a Safe wallet. Since Safe wallets are smart contracts, they [can not generate ECDSA signatures](https://ethereum.stackexchange.com/questions/122458/web3-eth-personal-sign-with-walletconnect-and-gnosis-safe/122469#122469). Therefore, Safe uses [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) for message signing and validating signatures. I mostly followed this [guide](https://docs.safe.global/safe-smart-account/signatures/eip-1271#verifying-a-signature) from Safe's documentation in order to implement the signature validation for when a user is using Safe. However, since we generate jwt's on the server side, I needed to do the check on both the frontend/backend.

Closes #1649 

### Approvals

- [x] Dev
- [x] Product

### CODE REVIEW

File: centrifuge-app/src/components/OnboardingAuthProvider.tsx [hunk 1]
```diff
@@ -222,20 +224,41 @@ Nonce: ${nonce}
...
+    body = JSON.stringify({
       message,
       signature: signedMessage,
       address,
       nonce,
       network: isEvmOnSubstrate ? 'evmOnSubstrate' : 'evm',
       chainId: evmChainId || 1,
-    }),
+    })
+  }
```
Comment (jpangelle) [inline centrifuge-app/src/components/OnboardingAuthProvider.tsx:253]: The contents of the `body` are conditional based on if the user is using a Safe wallet or a vanilla wallet.

**Review by sophialittlejohn — COMMENTED** [review]
Very nice job!! 

Since we're not using siwe directly it seems we may open up a vulnerability for replay attacks - we might want to consider implementing a similar strategy as we used for substrate auth where:
1. frontend calls /nonce where nonce is returned and set as server-only cookie
2. frontend calls /authenticateWallet and passes the returned nonce in request body
3. backend checks for presence of server-only cookie and confirms that the nonce in the cookie is the same as the once passed in the api request

File: onboarding-api/src/controllers/auth/authenticateWallet.ts [hunk 2]
```diff
@@ -33,13 +36,36 @@ const verifyWalletInput = object({
...
-    await validateInput(req.body, verifyWalletInput)
-    const payload = await new NetworkSwitch(req.body.network).verifiyWallet(req, res)
+    let payload
+
+    if ('safeAddress' in req.body) {
+      await validateInput(req.body, verifySafeInput)
+
+      const provider = new InfuraProvider(req.body.evmChainId, process.env.INFURA_KEY)
+      payload = await verifySafeWallet(provider, req.body.safeAddress, req.body.messageHash, req.body.evmChainId)
+    } else {
```
[the remark this answers is not in the document]
Comment (jpangelle) [reply onboarding-api/src/controllers/auth/authenticateWallet.ts]: Updated to more closely match the current pattern. I also implemented the usage of the `nonce`.

File: onboarding-api/src/utils/networks/evm.ts [hunk 3]
```diff
@@ -66,3 +68,72 @@ export async function verifyEvmWallet(req: Request, res: Response): Promise<Requ
...
+  const threshold = BigNumber.from(await safeContract.getThreshold()).toNumber()
+
+  if (!threshold || threshold > safeMessage.confirmations.length) {
+    throw new HttpError(400, 'Threshold has not been met')
+  }
+
+  const response = await safeContract.isValidSignature(messageHash, safeMessage?.preparedSignature)
+
+  if (response === MAGIC_VALUE_BYTES) {
+    res.clearCookie(`onboarding-auth-${safeAddress.toLowerCase()}`)
```
Comment (sophialittlejohn) [inline onboarding-api/src/utils/networks/evm.ts:114]: I think the cookie should be cleared whether the attempt is successful or not so that the nonce can't be reused

**Review by hieronx — APPROVED** [review]

File: centrifuge-app/src/components/OnboardingAuthProvider.tsx [hunk 4]
```diff
@@ -249,3 +274,50 @@ Issued At: ${new Date().toISOString()}`
     )
   }
 }
+
+const isValidSignature = async (provider: any, safeAddress: string, messageHash: string, evmChainId: number) => {
```
Comment (hieronx) [inline centrifuge-app/src/components/OnboardingAuthProvider.tsx:278]: Would be nice if this was abstracted into a helper that could be re-used between the onboarding API and the app at some point. Definitely a non-blocking improvement though!
