### PR TITLE
fix: asset sort

### LINKED ISSUE #1418: Add NFT ID column to asset details
Tinlake: 
Screenshot 2023-05-24 at 15 51 42

Centrifuge App:
Screenshot 2023-05-24 at 15 51 49

### PR DESCRIPTION
**Pull request by jpangelle**
### Description

This pull request
  - fixes the sorting logic for the `DataTable` component
  - adds a `NFT ID` column to the asset list
  - makes the column widths in the asset list more consistent

Closes #1418 

### Approvals

- [x] Dev
- [x] Product

### Screenshots

image

### CODE REVIEW

**Comment by annamehr** [comment]
All filters are working as well except of NFT id filter for BT4 pool. I also noticed that after an asset has been repaid the financing date is not displayed. 

Screenshot 2023-06-08 at 11 34 25

**Comment by annamehr** [comment]
Closes #1432

File: centrifuge-app/src/components/DataTable.tsx [hunk 1]
```diff
@@ -34,9 +37,15 @@ export type Column = {
 const sorter = <T extends Record<string, any>>(data: Array<T>, order: OrderBy, sortKey?: string) => {
   if (!sortKey) return data
   if (order === 'asc') {
-    return data.sort((a, b) => (a[sortKey] > b[sortKey] ? 1 : -1))
+    return data.sort((a, b) => {
+      if (sortKey === 'nftIdSortKey') return new BN(a[sortKey]).gt(new BN(b[sortKey])) ? 1 : -1
```
Comment (jpangelle) [inline centrifuge-app/src/components/DataTable.tsx:41]: to handle nft id's which are really large numbers
