### PR TITLE
Onboarding: Testing bugs

### LINKED ISSUE #1385: Onboarding bugs
1. In onboarding first step (Connect and link your wallet), if I deny the signing the first time, the ‘Continue’ button doesn’t work or give an error. In console, I see “MetaMask - RPC Error: MetaMask Personal Message Signature: User denied message signature.” — but I cannot get it to show the signing modal again unless I disconnect and reconnect my wallet.

2. If MetaMask auto-locks, it kicks me back to the start of onboarding. When I unlock metamask again, it kicks me back to the beginning of step 3, and I have to upload my ID/address/face again. :( It’s impossible to finish onboarding within MetaMask’s default lock out timer (3 minutes) with the time it takes to upload/verify documents — had to increase lock out time in MetaMask settings -> Advanced

----> can we increase the lock out time on our end?

4. Bug:  In onboarding step 3, I get a “please enter a valid email” error next to my email even though it’s a valid email. 

----> remove error when valid email is entered 

6. Not clear what to do if verification fails (e.g. due to a blurry photo). It's not clear that I can go back (and start over the whole uploading process again) by clicking on the icons at the left. 

---> add hint that user can go back and reupload documents
"If verification fails, please return and try uploading the requested documents again."

7. **Blocking issue (can’t finish onboarding): verify email link in KYC process leads to a link with an invalid cert: ** https://url8881.centrifuge.io/ls/click?upn=jx-2BPv7Ftmn-2F-2Bh-2ByvUzgBDn8Wt7y2ofI1cH3Bxr2OHAyGFFEJrv5QYMM3v4C72bvAID-2BkKsUEK-2BOVxPRURoKYrq4kMjDyc1JprbvKJnpCwctadzxG7FrPPXJMBxMZJ17oqzxrGFrIjh-2FrUPEo-2FABvUHbsTcNkMnNxq-2BE34VsMgpjOF4jbjSua9z-2Fxlsi9K-2BLgJ8ovebioS69Fu7cPFyrgU-2BQGU116oUbmAH6-2FJFEMr7thz-2B-2FmfAuxLQRiOkYZ0LQH3UPCRmQG54-2FAH1D8z-2BX4kNvRed5THC9eT9-2BQ-2Fu1t2fObjgvkhaQTrz2bitb6qhpxBAddthY6SS0KFeo-2FqIZJnNxEQ84mEfX6Awq5L2roaf9d2WxYpLaSjpR2l0aeVzKwoEi5L9LBJGbG7GlhRMCg3vSFutw88S-2BWGPqprywpZlI4H18kDX-2FIgyKB3CAHx5YD-2FVWv3Jm9JXqUr3a63N7auw-3D-3DhF8O_l7T1evsdeDpAdsYrmPx66ewD8O99Z6UGphVd0hTFToK3HvDDjSlw7YX-2B4slyMLySq-2FSnRRwX1s-2Bv-2FKUy144gTOrBx5XiqHy6Bh6j1vIHEplH7xYcLhAaWzZ7IR5CwYiu89xnki6rv2JN5HoP2pBIbTsK8UiDlU2natNUah8-2BxoUhj2CG2RRI1l54EhnluTJmaEYkjuWHg4qx5EJBecyPfyK9KgieqTBf3oUlL1t-2BylVkSvm2iVPqPuumep0ifIepLGy7RCCzPPhkjoOXm7UwLjmznBUJ3tSwlkSbqEPbzFa6RYGbtMHY8CTePlglA4qtw1J-2FzEF0MclKlf8o3a9-2BJw-3D-3D

8. In the KYC email verification email, the “investment disclaimer” and “privacy policy” hyperlinks lead to a link with an invalid certificate, example being for investment disclaimer: https://url8881.centrifuge.io/ls/click?upn=jx-2BPv7Ftmn-2F-2Bh-2ByvUzgBDo3CgyyNtIV7NG6R-2ByQOc2Ae6r6fLyBVvQwBKO-2BOCJHEn40HwjYcmuRxsNid-2FUB8qgopdEBbOi1xz88ewyb3j5c-3DIsuc_l7T1evsdeDpAdsYrmPx66ewD8O99Z6UGphVd0hTFToK3HvDDjSlw7YX-2B4slyMLySq-2FSnRRwX1s-2Bv-2FKUy144gTOrBx5XiqHy6Bh6j1vIHEplH7xYcLhAaWzZ7IR5CwYiu89xnki6rv2JN5HoP2pBIbTsK8UiDlU2natNUah8-2BxoUhj2CG2RRI1l54EhnluTJm3RWRNyuQB693yBKGSo9-2BdHXRnFqHKuvOXjkBc26LTfT7eQ7dXH6AXeTFJjb5OKw-2BQmedl21AmbVK1-2BHsL1LfDJZD2Gbpmon-2BbJr5xjxqw0Ow3qTFpzZ7F1HOZp9DjmrwyRxHhiKMKvsecelj0YqI5Q-3D-3D

9. “Next” button is already active before tax document is uploaded. 
image

### PR DESCRIPTION
**Pull request by sophialittlejohn**
### Description

This pull request...

Closes #1385

### Approvals

- [ ] Dev
- [ ] Dev
- [ ] Designer
- [ ] Product

### CODE REVIEW

File: centrifuge-app/src/pages/Onboarding/TaxInfo.tsx [hunk 1]
```diff
@@ -180,7 +180,7 @@ export const TaxInfo = () => {
           onClick={() => {
             isCompleted ? nextStep() : formik.handleSubmit()
           }}
-          disabled={isLoading}
+          disabled={isLoading || !formik.values.taxInfo || !formik.values.isEmailVerified}
```
Comment (jpangelle) [inline centrifuge-app/src/pages/Onboarding/TaxInfo.tsx:183]: I think `!formik.values.taxInfo` would disable the button if they uploaded, refreshed the page, and navigated back to the tax upload step.

I think it should be: `disabled={isLoading || (!formik.values.taxInfo && !taxInfoData) || !formik.values.isEmailVerified}`

**Review by jpangelle — APPROVED** [review]
