### PR TITLE
fix: replace hard coded value with ilk value

### LINKED ISSUE #232: Replace hardcoded maker ilk with the value in the pool config

### PR DESCRIPTION
**Pull request by jpangelle**
### Description

This pull request replaces the hard coded `RWA002-A` value with the `maker.ilk` value.

Also, the `check-format` CI job was failing because of formatting violations. I included those small fixes in this.

[mainnet preview](https://60bfce544512d846edce2dd6--staging-tinlake.netlify.app)

Closes #232

### CODE REVIEW

File: tinlake-ui/pages/pool/[root]/index.tsx [hunk 1]
```diff
@@ -8,9 +8,9 @@ import Header from '../../../components/Header'
 import WithFooter from '../../../components/WithFooter'
```
Comment (jpangelle) [inline tinlake-ui/pages/pool/[root]/index.tsx:8]: This file just contains `prettier` formatting fixes.

File: tinlake-ui/services/apollo/index.ts [hunk 2]
```diff
@@ -583,7 +583,7 @@ function toTinlakeLoans(loans: any[]): { data: Loan[] } {
```
Comment (jpangelle) [inline tinlake-ui/services/apollo/index.ts:583]: This file just contains `prettier` formatting fixes.

File: tinlake-ui/containers/Investment/View/TrancheOverview.tsx [hunk 3]
```diff
@@ -69,7 +69,7 @@ const TrancheOverview: React.FC<Props> = (props: Props) => {
 
   // V3 TODO: this should probably move to actions and expose a single TrancheData object (or to a duck?)
   const updateTrancheData = async () => {
-    dispatch(loadPool(props.tinlake, true))
+    dispatch(loadPool(props.tinlake, undefined, true))
```
Comment (jpangelle) [inline tinlake-ui/containers/Investment/View/TrancheOverview.tsx:72]: This feels a bit gross

**Review by offerijns — APPROVED** [review]
