### PR TITLE
approve token fix

### LINKED ISSUE #1548: Error: cannot estimate gas; transaction may fail or may require manual gas
## Bug report
I can’t invest in REIF while using  AllowInvestBelowMin - the error says Error: cannot estimate gas; transaction may fail or may require manual gas. Metamask won’t open the transaction signing window. An investor in CF4 reported the same error in their pool, that they can’t place a redemption order. The interesting twist is that I don’t have the same issue with New Silver pool. I can place an investment without any error using the same metamask wallet.

Screenshot 2023-08-10 at 14 54 42
Screenshot 2023-08-10 at 14 54 52

### PR DESCRIPTION
**Pull request by jpangelle**
### Description

This pull request addresses the issue with investing in a Tinlake pool.

Closes #1548 

### Approvals

- [ ] Dev
- [x] Product

### CODE REVIEW

File: centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx [hunk 1]
```diff
@@ -532,9 +532,14 @@ function InvestForm({ onCancel, hasInvestment, autoFocus, investLabel = 'Invest'
                 </Button>
               )}
             </Stack>
+            ``
```
Comment (onnovisser) [inline centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx:535]: `` ?

File: centrifuge-app/.env-config/.env.development [hunk 2]
```diff
@@ -11,7 +11,7 @@ REACT_APP_POOL_CREATION_TYPE=immediate
 REACT_APP_RELAY_WSS_URL=wss://fullnode-relay.development.cntrfg.com
 REACT_APP_SUBQUERY_URL=https://api.subquery.network/sq/centrifuge/pools-development
 REACT_APP_SUBSCAN_URL=
-REACT_APP_TINLAKE_NETWORK=goerli
+REACT_APP_TINLAKE_NETWORK=mainnet
```
Comment (onnovisser) [inline centrifuge-app/.env-config/.env.development:14]: left over from debugging I guess

**Comment by onnovisser** [comment]
Looking good, just 2 tiny comments

**Review by onnovisser — APPROVED** [review]
