### PR TITLE
Fix percentage of Junior held by provider in investment overview

### LINKED ISSUE #499: Invalid junior held by issuer
See https://tinlake.centrifuge.io/pool/0x3170D353772eD68676044f8b76F0641B2cbA084E/fortunafi-2. We're dividing the total number of TIN tokens held by the issuer, by the total TIN tranche value: https://github.com/centrifuge/apps/blob/main/tinlake-ui/containers/Investment/View/InvestmentOverview.tsx#L73. Instead, we should be dividing by the total TIN supply (the number of tokens instead of the value).

### PR DESCRIPTION
**Pull request by alessioscalici**
### Description

This pull request fixes the percentage of Junior held by provider, shown in the investment overview page

Closes #499
### Approvals

- [ ] Dev
- [ ] Product

### Impact

Pool overview page

### CODE REVIEW

**Review by onnovisser — APPROVED** [review]

File: tinlake-ui/containers/Investment/View/InvestmentOverview.tsx [hunk 1]
```diff
@@ -269,7 +270,7 @@ const InvestmentOverview: React.FC<Props> = (props: Props) => {
                     : undefined,
                   {
                     term: 'Junior provided by Issuer',
-                    value: reserveRatio ? parseFloat(juniorHeldByIssuer.toString()) / 100 : null,
+                    value: reserveRatio ? juniorHeldByIssuerPercentage.toString() : null,
```
Comment (offerijns) [inline tinlake-ui/containers/Investment/View/InvestmentOverview.tsx:273]: It was divided by `10e14` and then divided by 100 afterwards to keep 2 decimals precision. I think it should stay that way. The easiest to do that now is probably to multiple by `new BN('10000')` above and then to re add `/ 100` below.

**Review by offerijns — CHANGES_REQUESTED** [review]

**Review by offerijns — APPROVED** [review]
Nice 🙌
